scipy-lectures/scientific-python-lectures

- packages/sympy.rst
1. Added some math styling.
2. Added some lines to make dsolve work in Sympy 0.7.5.
I tried some stuff and is not working, e.g., equation In [8] hast a different output in Sympy 0.7.5. There is a mixture of inputs `>>>` and `In []`, is there any preference? is this arbitrary?
> Adding some math styling.

- intro/intro.rst
- Clarified the list,
- Corrected number of features,
At some point one should mention how to write comments and what is allowed as a variable name.
> Update with minor improvements

- advanced/image_processing/index.rst
- intro/scipy.rst
added +ELLIPSIS to make doctest involving matplotlib output pass
> make doctests pass for matplotlib output

- intro/scipy.rst
In order to make doctests work, the seed of the random number generator has been set and a file fname.png is created.
> make all doctest in scipy.rst work

- advanced/image_processing/index.rst
lena.png is created to let the doctest pass
> created lena to make doctest pass

- .travis.yml
- advanced/advanced_numpy/index.rst
- advanced/image_processing/index.rst
- advanced/mathematical_optimization/index.rst
- conf.py
- index.rst
- intro/matplotlib/matplotlib.rst
- intro/numpy/advanced_operations.rst
- intro/numpy/operations.rst
- intro/scipy.rst
- intro/summary-exercises/stats-interpolate.rst
Rebased version of #153 (which it superseeds)
This PR enables travis testing, and can be used to track the progress on making better tests.
> Test travis

- advanced/advanced_numpy/index.rst
- continuous_integration/install.sh
- intro/numpy/advanced_operations.rst
> Numpy doctests

- advanced/mathematical_optimization/index.rst
- intro/scipy.rst
note added in the scipy intro file
> remove use of anneal and add note on its deprecation

- advanced/advanced_numpy/index.rst
- advanced/image_processing/index.rst
- advanced/scipy_sparse/introduction.rst
- intro/image_processing/image_processing.rst
- intro/numpy/advanced_operations.rst
- intro/numpy/array_object.rst
- intro/numpy/exercises.rst
- intro/numpy/operations.rst
- intro/scipy.rst
- intro/summary-exercises/optimize-fit.rst
> DOCTESTS : switching backend for matplotlib

- advanced/advanced_numpy/index.rst
- intro/image_processing/image_processing.rst
- intro/summary-exercises/optimize-fit.rst
> Fix in intro/image_processing/image_processing.rst

- advanced/scipy_sparse/solvers.rst
> FIX - scipy dsolve has backward incompatible changes.

- advanced/scipy_sparse/dok_matrix.rst
> FIX dok matrices now support fancy indexing on one axis

- advanced/image_processing/index.rst
Working on fixing the image processing
> Try to fix image_processing

- intro/matplotlib/matplotlib.rst
Update of the the matplotlib mailing lists addresses
> Fix users and devel mailing lists addresses

- .travis.yml
- Makefile
- continuous_integration/install.sh
- packages/scikit-learn/index.rst
- packages/sympy.rst
Superseeds #183 and tries to fix the tests on top of it.
> Doctest packages

- .travis.yml
- advanced/advanced_numpy/index.rst
- advanced/advanced_python/index.rst
- advanced/image_processing/index.rst
- advanced/mathematical_optimization/index.rst
- advanced/scipy_sparse/bsr_matrix.rst
- advanced/scipy_sparse/coo_matrix.rst
- advanced/scipy_sparse/csc_matrix.rst
- advanced/scipy_sparse/csr_matrix.rst
- advanced/scipy_sparse/dia_matrix.rst
- advanced/scipy_sparse/dok_matrix.rst
- advanced/scipy_sparse/lil_matrix.rst
- advanced/scipy_sparse/solvers.rst
- intro/image_processing/image_processing.rst
- intro/language/basic_types.rst
- intro/language/control_flow.rst
- intro/language/first_steps.rst
- intro/language/io.rst
- intro/numpy/array_object.rst
- intro/numpy/elaborate_arrays.rst
- intro/scipy.rst
- intro/solutions.rst
- intro/summary-exercises/optimize-fit.rst
- packages/scikit-image/index.rst
- packages/scikit-learn/index.rst
Python 2.7 was actually being used.
I suspect that travis is going to fail on this PR and that we will have to fix things for Python 3
> [MRG] Enable Py3 tests on travis

- advanced/mathematical_optimization/examples/plot_gradient_descent.py
Fixes #187 : errors in optimization example
> [MRG] BUG: follow change in scipy.optimize.line_search

- conf.py
Small fix for the cover that uses `pdfpages` instead of `includegraphics`.
> Fix for the PDF cover

- packages/scikit-learn/index.rst
- link to the face recognition example, from `dev` branch to `stable`,
- fix weird sentence about image compression, add one remark explaining the value `K=5`.
> Improve one link, and fix one sentence

- intro/language/reusing_code.rst
While trying the example, I found reload as explained here did not work in Python3. Added how to do it in Python3.
> Calling reload in Python3

- continuous_integration/install.sh
Fix the continuous integration to follow upstream changes in miniconda.
Doing a pull request to get travis running.
> MAINT: follow changes in miniconda

- packages/statistics/index.rst
> Fix small typo

- continuous_integration/install.sh
- intro/scipy.rst
This PR should be merged after #235 for clarity
> Fix travis skip linalg det

- intro/numpy/array_object.rst
> add missing `plt.` namespace

- advanced/interfacing_with_c/ctypes/cos_module.py
I've been using this example during a lesson and it was not working on windows.
I had to use the added (commented) code. Unfortunately, I cannot test it anymore (I've been tested it on a student machine).
> Added (commented) case for windows

- LICENSE.rst
fixed a tiny typo in the license statement
> fixed typo in license statement

- advanced/advanced_numpy/examples/stride-diagonals-answer.py
- advanced/advanced_numpy/examples/stride-diagonals.py
- intro/language/exceptions.rst
- intro/numpy/exercises.rst
- intro/numpy/solutions/1_0_prime_sieve.py
- intro/numpy/solutions/2_4_mandelbrot.py
- intro/numpy/solutions/2_5_markov_chain.py
This PR addresses #243 by replacing `xrange` by `range` and using the new exception syntax of Python 3.
> removed Python 2 specific code

- .travis.yml
- continuous_integration/install.sh
follow http://conda.pydata.org/docs/travis.html
> Fix Python version inconsistencies in Travis

- advanced/mathematical_optimization/index.rst
- intro/matplotlib/examples/README.txt
- packages/scikit-image/examples/plot_boundaries.py
Just a few minor corrections...
> Correction of two typos and removal of a spurious word

- advanced/debugging/index.rst
- advanced/index.rst
- advanced/optimizing/index.rst
- intro/intro.rst
- intro/language/python_language.rst
- packages/index.rst
- packages/scikit-learn/index.rst
- themes/scipy_lectures/static/nature.css_t
* Mention the Jupyter notebook, Pycharm, Spyder: fixes #108
* Mention distributions: fixes #227
* Point clearly to Python 3: fixes #246
> Rewrite the intro chapter

- advanced/debugging/index_error.py
- advanced/debugging/segfault.py
- advanced/debugging/to_debug.py
- advanced/debugging/to_debug_solution.py
This commit adds parentheses for Python's print function. This way the code not
only "works" on Python 2, but also on Python 3.
> Add parentheses for print function

- advanced/image_processing/examples/plot_geom_face.py
Fixes build with sphinx-gallery
> use explicit integer division

- advanced/advanced_numpy/index.rst
- conf.py
- intro/matplotlib/index.rst
- intro/numpy/exercises.rst
- intro/numpy/operations.rst
- intro/scipy.rst
- packages/3d_plotting/index.rst
- packages/statistics/index.rst
- packages/sympy.rst
* sphinx.ext.pngmath is deprecated/replaced with sphinx.ext.imgmath
* Some external packages URL have changed
* Use the seealso directive
* Fix a bunch of warnings (mostly broken references)
> MAINT: update conf.py + layout + fix warnings

- advanced/image_processing/index.rst
- advanced/mathematical_optimization/index.rst
- continuous_integration/install.sh
- intro/scipy.rst
- packages/scikit-learn/index.rst
A branch to fix the failing test (it looks like it's a bug of the CI).
> MRG: Fixing CI

- advanced/mathematical_optimization/examples/helper/compare_optimizers.py
* change iteritems to items: This also works with python2, but it needs a bit more memory.
* print is now a function, so add parentheses
* in line 154 and 158 this_costs is an tuple and I think we want to get the first element
> Change script that in run under python3

- intro/language/basic_types.rst
fixed a typo in the description of the triple quotation
> typo in strings triple quotation

- intro/language/functions.rst
In Fibonacci sequence, u_0 is 0, not 1.
Switch to latex for better rendering
> Fix Fibonacci example and switch to latex

- advanced/mathematical_optimization/examples/plot_1d_optim.py
- advanced/mathematical_optimization/examples/plot_constraints.py
- advanced/mathematical_optimization/examples/plot_exercise_flat_minimum.py
- advanced/mathematical_optimization/examples/plot_exercise_ill_conditioned.py
- advanced/mathematical_optimization/examples/plot_non_bounds_constraints.py
- advanced/mathematical_optimization/examples/plot_smooth.py
The file plot_gradient_descent.py is still missing, though. I will try to do that this evening.
> Switch script to new minimize API

- advanced/image_processing/index.rst
- advanced/mathematical_optimization/index.rst
- intro/numpy/gallery.rst
- intro/numpy/index.rst
- packages/scikit-image/index.rst
This PR addresses #270. Hopefully, I did not miss a chapter containing figures.
> Galleries at end of chapters added

- CHANGES.rst
Just a correction of a minor typo.
> typo corrected

- intro/matplotlib/index.rst
Update the matplotlib chapter:
- Reference jupyter in addition to IPython
- Many small style changes (clear floats to look better on small screens, integrate the gallery, put hints after question, use hlist)
> Matplotlib: maintenance and style

- advanced/mathematical_optimization/examples/helper/compare_optimizers.py
- advanced/mathematical_optimization/examples/plot_gradient_descent.py
This PR uses the new optimize.minimize API also in the programs plot_gradient_descent.py and helper/compare_optimizers.py. This PR also completes the migration to the new API.
However, there is still a problem in helper/compare_optimizers.py. For the solver L-BFGS_B I get the warning
``OptimizeWarning: Unknown solver options: factr``.
According to the documentation, https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html, this option does exist. Unfortunately, I don't have time to investigate this issue myself.
If nobody has time to look at the problem right now, the best way would be to create a new issue, while closing the issues #215 and #300 .
> Scipy optimize

- CONTRIBUTING.rst
After #332 has been merged, the html build works also for Python 3. I adapted the text accordingly.
> adapted description to Python 3

- build_tools/install.sh
- circle.yml
I had a look at the output artifacts, and everything seems to build well under Python 3.
> [MRG] MAINT: switch circle to Python 3

- CONTRIBUTING.rst
This PR implements changes as discussed in #335.
> Improvement of requirement/build information

- environment.yml
- requirements.txt
This PR is to test the CI against scikit-image 0.13
> update scikit-image to 0.13

- intro/matplotlib/index.rst
Fixed a broken link and corrected a single word, both in the matplotlib chapter.
> two small matplotlib fixes

- packages/statistics/index.rst
I read through and made some updates to the statistics section. Updated some of the code, and rewrote a few sentences.
> Updated statistics section

- index.rst
Rendering looks better then, all text in box
se temporary deployment https://nameless-taiga-53135.herokuapp.com/index.html
> Remove bullet points in sidebar

- CONTRIBUTING.rst
> Document release

- CONTRIBUTING.rst
- guide/index.rst
> Contributing and style

- intro/language/control_flow.rst
> typo pointed out in #378 corrected

- themes/scipy_lectures/static/nature.css_t
> CSS: try to fix high-density displays

- intro/numpy/array_object.rst
> Removed unneeded final comma

- intro/intro.rst
Added a warning about Python 2 deprecation
> Warning Python 2 EOL

- packages/scikit-learn/index.rst
> Fix Incorrect figure in scikit-learn

- intro/intro.rst
It offers excellent python and anaconda support and I think it should be included to the list
> Include Visual Studio Code to intro

- advanced/optimizing/index.rst
Fixed small typo: seperation -> separation
> Fixed small typo: seperation -> separation

- packages/statistics/index.rst
> fix typo: indivuals -> individuals

- intro/scipy/examples/plot_2d_minimization.py
This PR fixes the incorrect origin used by ``imshow`` (cf. #438).
> problem with origin mentioned in #438 fixed

- intro/matplotlib/examples/plot_axes-2.py
- intro/matplotlib/examples/plot_axes.py
This PR fixes the typo mentioned in #435 and makes the use of zeros in floating point numbers consistent.
> fixes #435

- advanced/interfacing_with_c/interfacing_with_c.rst
> Tiny typo fix

- advanced/debugging/index.rst
> update instructions for flymake emacs mode.

- advanced/advanced_numpy/index.rst
> remove obsolete example for inplace operations

- CONTRIBUTING.rst
This PR proposes an implementation of the ideas of @pdebuyl in #434.
> objectives and design choices added

- advanced/image_processing/index.rst
- intro/summary-exercises/examples/plot_sprog_annual_maxima.py
- intro/summary-exercises/stats-interpolate.rst
- fix broken internal sphinx gallery links in 1.5.11 and 2.6
- remove dead code in plot_sprog_annual_maxima.py
see #444
> Fix sphx links

- advanced/debugging/index.rst
> replace suggestions for debugging environments

- intro/index.rst
- intro/python_2_python_3.rst
> add python 2/3 section in intro

- intro/numpy/operations.rst
The example is already in the exercises.
Part solution of #94
> remove hares lynxes carrots examples from chapter

- intro/matplotlib/examples/exercises/plot_exercise_1.py
Simple typo on matplotlib exercise 1 comment fixed.
> Typo fixed.

- packages/3d_plotting/index.rst
- packages/scikit-learn/index.rst
This PR is sort of a follow-up on #494 correcting the same mistake in two more places.
> two typos corrected

- .github/workflows/circleci.yml
This may need some settings changed on the repo. But I can't remember for sure. Once this is merged, if it doesn't work, I will look into what settings need to be changed and let you know since I don't have access to make changes myself.
> Use GH actions to link to doc artifact

- index.rst
- themes/scipy_lectures/layout.html
Here is what I think needs to be done:
- https://github.com/ipython/ipython/settings/branches
```
git branch -m master main
git fetch <YOUR_UPSTREAM_REMOTE>
git branch -u <YOUR_UPSTREAM_REMOTE>/main main
(where YOUR_UPSTREAM_REMOTE is typically called `upstream` or `origin`)
```
The whole process should only take a few minutes.
> Rename master to main

- .github/workflows/test.yml
- Makefile
We can add more tests later, but I would prefer to have this merged sooner rather than later. It will make it easier to be confident about other janitorial PRs.
The tests fail on macos and windows, but it looks like they may never have been intended to run on different OSes. We should probably reconsider this at some point.  For now, I plan to just make a small number of updates that will want regardless.
> Run basic tests

- advanced/mathematical_optimization/examples/plot_exercise_ill_conditioned.py
- advanced/mathematical_optimization/index.rst
- advanced/optimizing/demo.py
- advanced/optimizing/demo_opt.py
- advanced/optimizing/ica.py
- advanced/optimizing/index.rst
- intro/numpy/exercises.rst
- intro/numpy/operations.rst
- intro/numpy/solutions/2_5_markov_chain.py
- intro/scipy.rst
> Use matrix multiplication operator

- intro/scipy.rst
- intro/scipy/examples/plot_solve_ivp_damped_spring_mass.py
- intro/scipy/examples/plot_solve_ivp_simple.py
> Use solve ivp

- advanced/advanced_numpy/index.rst
- advanced/image_processing/examples/plot_face.py
- advanced/image_processing/index.rst
- advanced/scipy_sparse/solvers.rst
- intro/numpy/advanced_operations.rst
- intro/scipy/index.rst
Before PR
```
======================= 40 passed, 22 warnings in 24.04s =======================
```
After
```
======================= 40 passed, 13 warnings in 20.29s =======================
```
> Fix more doctest warnings

- advanced/image_processing/examples/plot_watershed_segmentation.py
- packages/scikit-image/examples/plot_segmentations.py
- packages/scikit-image/index.rst
Down to just 7 warnings with `make test`!
> Fix peak index usage; remove deprecated skimage.viewer example

- requirements.txt
This is just to trigger the error. I still need to track down a fix...
```
Unexpected failing examples:
/home/circleci/project/packages/statistics/examples/plot_wage_data.py failed leaving traceback:
Traceback (most recent call last):
File "/home/circleci/project/packages/statistics/examples/plot_wage_data.py", line 62, in <module>
seaborn.pairplot(data, vars=['WAGE', 'AGE', 'EDUCATION'],
File "/home/circleci/venv/lib/python3.10/site-packages/seaborn/axisgrid.py", line 2144, in pairplot
grid.map_diag(histplot, **diag_kws)
File "/home/circleci/venv/lib/python3.10/site-packages/seaborn/axisgrid.py", line 1507, in map_diag
func(x=vector, **plot_kwargs)
File "/home/circleci/venv/lib/python3.10/site-packages/seaborn/distributions.py", line 1418, in histplot
color = _default_color(method, hue, …
```
> Remove matplotlib pin 

- .gitignore
- packages/statistics/examples/plot_airfare.py
- packages/statistics/examples/plot_wage_data.py
- requirements.txt
Could have used a submodule of urllib, but urllib.request may be deprecated in the future according to docs.
> Change downloads to use `requests`

- packages/scikit-image/index.rst
I had to add this, to make the block run by itself.
> Make code block self-contained

- advanced/debugging/wiener_filtering.py
- advanced/image_processing/examples/plot_block_mean.py
- advanced/image_processing/examples/plot_blur.py
- advanced/image_processing/examples/plot_display_face.py
- advanced/image_processing/examples/plot_face.py
- advanced/image_processing/examples/plot_face_denoise.py
- advanced/image_processing/examples/plot_face_tv_denoise.py
- advanced/image_processing/examples/plot_geom_face.py
- advanced/image_processing/examples/plot_interpolation_face.py
- advanced/image_processing/examples/plot_numpy_array.py
- advanced/image_processing/examples/plot_radial_mean.py
- advanced/image_processing/examples/plot_sharpen.py
- advanced/image_processing/index.rst
- intro/numpy/exercises.rst
- intro/scipy/examples/plot_image_filters.py
- intro/scipy/examples/plot_image_transform.py
- intro/scipy/image_processing/image_processing.rst
- packages/scikit-image/index.rst
- requirements.txt
> Update scipy datasets path

- intro/scipy/index.rst
- intro/scipy/summary-exercises/stats-interpolate.rst
Update the interpolate section.
`scipy.interpolate.interp1d` is deprecated so I replaced with something that we do recommend now.
> Update sp.interpolate section

- intro/scipy/index.rst
Update of `scipy.special` section.
> MAINT: update scipy.special section

- intro/scipy/index.rst
Followup to gh-576. Might be overkill.
> ENH: add information about numerical tricks

- intro/numpy/operations.rst
- themes/scientific_python_lectures/static/nature.css_t
> Fix img float

- themes/scientific_python_lectures/layout.html
- themes/scientific_python_lectures/static/nature.css_t
> Further clean up tip display

- packages/statistics/index.rst
This adjusts the SciPy portion of the chapter, but I wouldn't be a good person to work on the rest.
Also, we might want to pick a different example or adjust the language surrounding the male/female distinction.
> MAINT: update statistics section

- Makefile
- advanced/advanced_numpy/index.rst
- advanced/advanced_python/index.rst
- advanced/image_processing/index.rst
- advanced/mathematical_optimization/index.rst
- advanced/scipy_sparse/bsr_matrix.rst
- advanced/scipy_sparse/coo_matrix.rst
- advanced/scipy_sparse/csc_matrix.rst
- advanced/scipy_sparse/csr_matrix.rst
- advanced/scipy_sparse/dia_matrix.rst
- advanced/scipy_sparse/dok_matrix.rst
- advanced/scipy_sparse/introduction.rst
- advanced/scipy_sparse/lil_matrix.rst
- advanced/scipy_sparse/solvers.rst
- intro/matplotlib/index.rst
- intro/numpy/advanced_operations.rst
- intro/numpy/array_object.rst
- intro/numpy/elaborate_arrays.rst
- intro/numpy/exercises.rst
- intro/numpy/operations.rst
- intro/scipy/image_processing/image_processing.rst
- intro/scipy/index.rst
- intro/scipy/summary-exercises/stats-interpolate.rst
- packages/scikit-image/index.rst
- packages/scikit-learn/index.rst
- packages/statistics/index.rst
- packages/sympy.rst
- pytest.ini
> Cleanup testing configuration

- pytest.ini
> Ignore boolean index warning temporarily

- intro/language/control_flow.rst
> Fix literal compare warning

- intro/numpy/exercises.rst
> Suggest `argmin` rather than `argsort` for distance exercise

- .github/workflows/pages.yml
Also set the committer to github-actions[bot]
> Only keep the last build on gh-pages branch

- advanced/image_processing/index.rst
- intro/scipy/image_processing/image_processing.rst
- pytest.ini
This reverts commit e39b3307558f49f65ddf33e7158ee547437509a4. See #626 and #628.
Waiting on the resolution of https://github.com/scipy/scipy/issues/18780
> Fix boolean index warning

- advanced/scipy_sparse/bsr_matrix.rst
- advanced/scipy_sparse/coo_matrix.rst
- advanced/scipy_sparse/csc_matrix.rst
- advanced/scipy_sparse/csr_matrix.rst
- advanced/scipy_sparse/dia_matrix.rst
- advanced/scipy_sparse/dok_matrix.rst
- advanced/scipy_sparse/examples/README.txt
- advanced/scipy_sparse/examples/direct_solve.py
- advanced/scipy_sparse/examples/lobpcg_sakurai.py
- advanced/scipy_sparse/examples/pyamg_with_lobpcg.py
- advanced/scipy_sparse/index.rst
- advanced/scipy_sparse/introduction.rst
- advanced/scipy_sparse/lil_matrix.rst
- advanced/scipy_sparse/solvers.rst
- advanced/scipy_sparse/storage_schemes.rst
Changes the descriptions from sparse matrices to sparse arrays.
Updates the descriptions.
I didn't add any new "other packages", but that could be updated.
> update lectures for sparse arrays

- intro/language/basic_types.rst
> Fix display issue for assignment operator section

- index.rst
> Fix icons width

- .pre-commit-config.yaml
> Move the pre-commit prettier mirror

- advanced/mathematical_optimization/index.rst
The function value mentioned in the description before the program in the section "13.2.1 Getting Started: 1D Optimization" differs from the value used in the program. To minimize changes, I updated the value of 'a' in the function f(x) = exp[(x - a)^2] from 0.7 to 0.5 in the description.
> Fix value error: 0.7 -> 0.5

- requirements.txt
See https://github.com/numpy/numpy/issues/27957
> Update NumPy (2.2)
