intro/numpy/array_object.rst
Reference to `unit32` and `unit64` data types corrected to `uint32` and `uint64`.
=> Correct typo in data types section

advanced/mathematical_optimization/index.rst
Some remarks:
* In contrast to the previous behavior, the example for simulated annealing works just fine for the seed 
chosen. If the example should not behave so well, may be another seed needs to be chosen.
* In line 954, doctest complained about `unexpected EOF while parsing` even though everything seemed 
syntactically correct. As a temporary solution, I removed the linebreak, but this should in principle not be
necessary.
* A problem remains in line 995 where some of the output of subroutine COBYLA is not considered as output
by doctest. It could be removed to make the doctest work, but on the other hand, the user will have this 
output displayed when running the example. Therefore, it probably should be presented in the lecture notes. 
Replacing it by an ellipsis also does not seem …
=> make (almost all) doctests pass in mathematical_optimization

advanced/mathematical_optimization/index.rst
After rerunning the tests, it seems that there are still two problems which this PR attempts to solve.
* In one case a random seed has to be set.
* In another case, it seems that the output of `optimize.fmin_l_bfgs_b` got lost. It is restored with this PR.
=> make two failing doctests in mathematical_optimization pass

advanced/image_processing/index.rst
Changes to make doctest past.
Please check.
Current version of nd scipy.ndimage has probably
changed since the tutorial was written and gives
slightly different numerical output
In particular see 699-671
Argment names in function
sklearn.cluster.spectral_clustering
have changed (line 727)
nb_labels (line 755) is now different
=> Fixes in image_prossessing/index.rst

intro/language/exceptions.rst
Double negative makes the first sentence difficult to follow.
=> remove double negative in intro paragraph

AUTHORS.rst, Makefile
Created a makefile rule to list all contributors to be listed at the end of AUTHORS.rst (alphabetical order on last name)
$ make contributors
- arunpersaud
- Matthew Brett
- Lars Buitinck
...
Possible issues:
* Some entries are only github usernames because the account holder has not provided his or her full name
* Should names be include here which are already in the "Chapter authors" section?
* All contributors are listed, even if they only made a single commit with a spell fix. That can be discussed but I have chosen not to exclude anyone here.
/Olav
=> Issue 66: update authors list

intro/image_processing/image_processing.rst
Following the conversion from an IPython-style to a Python-style code example, the code example ended up being interpreted as an incorrect figure caption. The code example thus effectively had disappeared. This PR corrects the problem and restores the code example.
=> corrected rst to restore code example

advanced/optimizing/index.rst
The `literalcode` directive does not accept the keyword `start_line`. Therefore, the code example did not appear in the output. Probably the most stable way to include the code segment is the `pyobject` keyword used in this PR.
=> make code example visible

LICENSE.rst
Just a proposal to upgrade the CC-BY 3.0 United state to CC-BY 4.0 International.
I'm not quite qure what is the difference but if Creative Commons upgraded the CC-BY, maybe they detected some problem with the 3.0. Also, not quite sure about the advantage of the US version compared to the international one.
=> Upgrade CC-BY 3.0 US to CC-BY 4.0 international

advanced/advanced_numpy/index.rst, advanced/mathematical_optimization/index.rst, guide/index.rst, intro/language/functions.rst, intro/scipy.rst
These changes aim to fix the folloing errors:
scipy-lecture-notes/advanced/advanced_numpy/index.rst:488: ERROR: Inconsistent literal block quoting.
scipy-lecture-notes/advanced/mathematical_optimization/index.rst:890: ERROR: Unexpected indentation.
scipy-lecture-notes/guide/index.rst:93: ERROR: Unknown directive type "literal-include". 
scipy-lecture-notes/intro/language/functions.rst:384: ERROR: Unexpected indentation.
scipy-lecture-notes/intro/language/functions.rst:387: ERROR: Unexpected indentation. 
scipy-lecture-notes/intro/scipy.rst:452: ERROR: Unexpected indentation.
=> Fix html build errors

packages/scikit-learn/index.rst
Fixes a few typing mistakes on [packages/scikit-learn/index.rst](http://www.scipy-lectures.org/advanced/scikit-learn/) (like Excercise → Exercise).
=> Fixed small typos on packages/scikit-learn/index.rst

advanced/scipy_sparse/other_packages.rst
The project PyAMG has moved to github.
=> Updated the broken link to PyAMG

intro/scipy.rst
=> Small changes on intro/scipy (mainly scipy.integrate)

continuous_integration/install.sh
The dependence of NumPy on libgfortran has changed in conda, see
https://github.com/conda/conda/issues/2177
=> add conda install of libgfortran=1

intro/numpy/array_object.rst
Without this fix, if you would replace the number 100 by the number 5 in the line
```python
is_prime = np.ones((100,), dtype=bool)
```
you would get the wrong result that 4 is a prime number!
(More generally, this would occur everytime you take any number of the form $p^2+1$, where $p$ is some prime number.)
=> Fix of the Prime Sieve example

advanced/advanced_numpy/examples/mandel-answer.pyx, advanced/advanced_numpy/examples/mandel.pyx, advanced/advanced_numpy/index.rst
Updates to Advanced NumPy chapter:
* creating ufuncs: NumPy ships with Cython definitions, so no more need to pull stuff from NumPy C-headers
* generalised ufuncs: NumPy >= 1.8 ships with public g-ufuncs in linalg module
=> Advanced numpy updates

circle.yml, continuous_integration/circle_ci_test_doc.sh, continuous_integration/install.sh
Some modifications necessary in continuous_integration/install.sh to make it compatible with both Travis and CircleCI.
Also for now tests are not run on CircleCI because there are plenty of errors I don't understand.
Fixes #244.
=> Add documentation generation on CircleCI

intro/matplotlib/examples/plot_bar.py, intro/matplotlib/examples/plot_boxplot.py, intro/matplotlib/examples/plot_contour.py, intro/matplotlib/examples/plot_grid.py, intro/matplotlib/examples/plot_imshow.py, intro/matplotlib/examples/plot_multiplot.py, intro/matplotlib/examples/plot_pie.py, intro/matplotlib/examples/plot_plot.py, intro/matplotlib/examples/plot_plot3d-2.py, intro/matplotlib/examples/plot_plot3d.py, intro/matplotlib/examples/plot_polar.py, intro/matplotlib/examples/plot_quiver.py, intro/matplotlib/examples/plot_scatter.py, intro/matplotlib/examples/plot_text.py
There is value is having the examples run also on more recent MPL versions, as this is more likely to be what users have. They should still run well on older versions.
The changes are only in examples that are actually used to generate figures, but not as real examples. They make code a bit more complicated, but I couldn't adapt to MPL 1.5 without that.
=> Adapt examples to MPL 1.5

.travis.yml
Using environment variables, as PYTHON_VERSION="$TRAVIS_PYTHON_VERSION"
does not seem to work.
While I was at it, I removed the virtualenv section which is not needed.
Build from master showing that Python 2.7 is used in the Python 3.4 build:
https://travis-ci.org/scipy-lectures/scipy-lecture-notes/jobs/155856706#L565
Build from my branch showing that Python 3.4 is used in the Python 3.4 build (as it should be):
https://travis-ci.org/lesteve/scipy-lecture-notes/jobs/155877711#L562
=> Fix Travis Python 3 build

advanced/advanced_numpy/index.rst, intro/numpy/advanced_operations.rst, intro/numpy/array_object.rst, intro/numpy/index.rst, intro/numpy/operations.rst
Following a recent discussion on NumPy [maliling list](https://mail.scipy.org/pipermail/numpy-discussion/2016-August/075911.html) and the resulting PR numpy/numpy#8021, I recommend  to change all instances of Numpy to NumPy (capital N and P), when the lectures refer to the project.
These are automatic search-and-replace changes done  by running the command:
```
$ find . -name "*.rst" -exec sed -i -e 's/Numpy/NumPy/g' {} \;
```
on advanced/advanced_numpy and intro/numpy directories.
See issue #250.
=> update NumPy spelling

packages/3d_plotting/index.rst
I flipped the images, structured and unstructed were mixed up.
=> Mayavi example images are flipped

advanced/image_processing/index.rst, intro/numpy/array_object.rst, intro/numpy/operations.rst, pyplots/numpy_intro_5.py
np.random.random_integers() is depricated in numpy 1.11, we better use np.random.randint() instead.
=> Changing random_intergers() to randint()

advanced/advanced_python/index.rst
There was inconsistency as far as usage of singular vs plural ("a function or a class are" -> "functions and classes are", since the rest of the paragraph uses it as plural). Also removed an extra space
=> 2.1.2 - Plural inconsistency fix

advanced/debugging/index.rst
Saw this while reading the debugging part. I guess this was a typo.
=> Fix spelling of gdb from gbd

advanced/image_processing/examples/plot_face_tv_denoise.py
From the [0.12 release notes](https://github.com/scikit-image/scikit-image/blob/master/doc/release/release_0.12.rst#api-changes):
> skimage.filters.denoise_* have moved to skimage.restoration.denoise_*.
=> [MRG] Fix plot_face_tv_denoise.py with skimage >= 0.12

intro/numpy/array_object.rst
It is very sensitive to the version of numpy, etc, and will fail even when CI
testing is good.
=> Shorten ellipsis for the output of np.array?

advanced/mathematical_optimization/index.rst
SciPy 0.11 added a general function to compute the minimum of a scalar function, minimize_scalar. Change the disscussion from brentq to minimize_scalar.
=> Switch from brentq to minimize_scalar

packages/sympy.rst
Two things here (happy to revert to simplify the PR):
1. 917a602 implements the discussion at #297: changes `from sympy import *` to `import sympy as sym`.
2. fdfa8ca changes the `init_printing` call: it was called at the start (in a hidden `TODO`) and then called again to show the reader. However this would result in no change of behaviour. This didactically shows the effect of calling `init_printing`.
=> Unflatten sympy namespace

packages/sympy.rst
Closes #308.
This fixes a number of outputs that were not being doctested (the
Jupyter `In` `Out` prompt was being used which is not recognised by the
python doctest module).
Note that I did not change `sym.solve` for the case of the system of
equations (the alternatives are not yet implemented in solveset and I feel
make things more complicated than they need to be). FWIW in my own
teaching I do not consider systems of linear equations using any of the
solvers and instead show students how to use Numpy (or indeed Sympy) to
do this using matrices.
=> Move from sym.solve to sym.solveset.

index.rst, themes/scipy_lectures/static/nature.css_t
CSS tweek to reenable "font boosting", used by chrome to automatically adjust font size for mobile devices.
A preview is visible on http://gael-varoquaux.info/scipy-lecture-notes/
Check it out with your phone.
=> CSS: fix font size on mobile phones

conf.py
According to sphinx's documentation, a stand-alone latex_preamble variable is
deprecated since version 0.5 http://www.sphinx-doc.org/en/1.5.6/config.html
=> include latex_preamble in latex_elements

themes/scipy_lectures/static/nature.css_t
This is done by adding a custom css file that acts on the ".gp" and ".go" classes.
=> make prompt '>>>' and output unselectable

packages/scikit-learn/examples/plot_svm_non_linear.py
This is needed for proper building of the examples with sphinx.
=> Use double slashes for integer division

advanced/interfacing_with_c/interfacing_with_c.rst, advanced/interfacing_with_c/python_c_api/cos_module.c
Make the c module in `advanced/interfacing_with_c/python_c_api/cos_module.c` 2/3 compatible.
Add a note about the filenames of Python 3 extensions in the corresponding text.
Finishes #225 that was only Python 3 compatible.
=> Fix c module python 2 3

CONTRIBUTING.rst
This PR adds a rather explicit description of how to set up a miniconda environment to produce the lecture notes in html and pdf format. In this way, at least users on Linux and MacOS should be able to use the same environment as the one used in the tests. I kept the requirements and Fedora sections even though they seem outdated and might not be needed anymore.
=> Building instructions for Debian/Ubuntu added

CONTRIBUTING.rst
Remove the Fedora build instructions. Nobody in the team currently uses
Fedora and can check the instructions.
Provide generic instructions based on pip instead.
=> Replace Fedora build instructions with generic ones

Makefile, conf.py
The previous setting was wrong and sphinx used the default setting.
The setting must be `a4paper` and not `a4`. I placed it in `conf.py` instead of command-line arguments in the Makefile. The cover is a4 anyway and won't fit in letter format.
=> fix the sphinx settings for papersize

intro/numpy/array_object.rst
The example code was for a 1d plot, I used the code from plot_basic2dplot.py
instead.
Fixes #358
=> Replace wrong code for the basic 2d plot

advanced/image_processing/index.rst
The code examples for interpolating the face image show no option being passed to `interpolation`, then `nearest` being passed. 
However the images first show a smooth interpolation, followed by the rough `nearest`. I'm not sure if the default used to be bilinear, but now when you run the examples, the default of `interpolation=none` is the same as `nearest`, so you get two of the same result if you copy paste the code.
I also added the link to the matplotlib interpolation example because it is a quick illustrator to the types you can choose from
=> Fix the interpolation code to match the images

build_tools/install.sh
Purpuse of this section is to deactivate a default virtual environment provided
by travisi
Rather than testing on the absence of a CIRLCE_CI variable, test on TRAVIS
instead which is given for all builds with default value "true"
=> For travis builds, test on TRAVIS environment var

intro/language/basic_types.rst
This PR takes care of #377 by adding a comment. In addition the comment lines in the first code example of that section are shifted down by one line to avoid the comment to become part of the string `s`.
=> comment added in view of #377

advanced/optimizing/index.rst
vbench is no longer maintained, and replaced in usage by asv
=> Optimization chapter: link to asv instead of vbench

packages/statistics/examples/plot_iris_analysis.py
The environment.yml file asks for pandas 0.20. There was change back in version 0.15.  
Rename `categorical_instance.labels` to `categorical_instance.codes` (pandas >= 0.15)
See: https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v0.15.0.txt
The ``Categorical.labels`` attribute was renamed to ``Categorical.codes``.
=> Update to renaming in pandas 0.15

advanced/interfacing_with_c/numpy_c_api/cos_module_np.c
As in 258d192b, the numpy C-API code needs to be updated to work with both python 2 and 3.  For stylistic reasons, I tried to follow that previous commit as closely as possible — but there are additional changes needed for numpy that make the difference a little more extensive.
=> make cos_module_np 2/3 compatible

intro/language/python_language.rst
Existing link http://www.diveintopython.net/ no longer pointed to the proper website.
=> Corrected link to Dive into Python

intro/intro.rst, intro/language/first_steps.rst, intro/numpy/array_object.rst
Most of the changes reflect the fact, that ipython3 (not ipython) needs to be executed in Linux to get IPython with Python 3.
Plus the removal of trailing whitespace.
=> Small additions

intro/scipy.rst
I believe in the damped oscillator example, there's a factor $2$ missing in the calculation of the derivative vector.
=> Fix math error

intro/scipy.rst, intro/scipy/examples/plot_normal_distribution.py, intro/scipy/examples/plot_t_test.py
This PR takes care of the deprecated keyword argument ``normed`` of  ``np.histogram`` pointed out in #439. A related deprecation applies to ``plt.hist`` since ``matplotlib 2.2`` which we presently use to build the lecture notes. Therefore, this PR also replaces ``normed`` by ``density`` in calls to ``plt.hist``.
=> deprecated keyword argument replaced

intro/numpy/operations.rst
distance to origin example is shown for 5x5 grid, but text said 10x10
=> small text update in broadcasting example

intro/matplotlib/examples/exercises/plot_exercise_1.py, intro/matplotlib/examples/exercises/plot_exercise_10.py, intro/matplotlib/examples/exercises/plot_exercise_2.py, intro/matplotlib/examples/exercises/plot_exercise_3.py, intro/matplotlib/examples/exercises/plot_exercise_4.py, intro/matplotlib/examples/exercises/plot_exercise_5.py, intro/matplotlib/examples/exercises/plot_exercise_6.py, intro/matplotlib/examples/plot_bad.py, intro/matplotlib/examples/plot_good.py, intro/matplotlib/examples/plot_plot.py, intro/matplotlib/examples/plot_ugly.py, intro/matplotlib/examples/pretty_plots/plot_boxplot_ext.py, intro/matplotlib/index.rst
There is no need to specify this explicitly because it is already the
default behavior.
=> remove endpoint=True from np.linspace()

intro/language/control_flow.rst
This PR addresses the pretty old issue #81. As it seems not completely useless to me to at least mention list comprehensions, I added a short sentence trying to motivate the following example. Of course, much more could be said about list comprehensions and alike, but here is probably not the place for it.
=> remark on list comprehensions added

packages/statistics/index.rst
This is just to make Sphinx happy and to avoid a warning.
=> length of title underline increased

CHANGES.rst, advanced/advanced_numpy/index.rst, advanced/advanced_python/index.rst, advanced/interfacing_with_c/interfacing_with_c.rst, advanced/mathematical_optimization/index.rst, guide/index.rst, intro/help/help.rst, intro/intro.rst, intro/language/basic_types.rst, intro/matplotlib/index.rst, packages/scikit-image/index.rst, packages/scikit-learn/examples/plot_eigenfaces.py, packages/statistics/index.rst, packages/traits/index.rst
`make linkcheck` listed 26 links as broken. In some cases, where the commit message explains my reasoning, it might be worth checking my replacement. There remain four broken links where I was not completely sure what to do:
* http://www.euroscipy.org/talk/882: The archive is presently not working but there are chances that this content might be reactivated.
* http://scipy.org/Developer_Zone/UG_Toc: Here, I was not quite sure what the original intention was.
* http://www.plope.com/Members/chrism/flymake-mode: see #452 for more details
* http://winpdb.org/: see #453 for more details
=> fixed most of the broken links

advanced/image_processing/examples/plot_face.py, advanced/image_processing/index.rst, intro/numpy/advanced_operations.rst, intro/scipy.rst, requirements.txt
The SciPy routines are deprecated. imageio is the recommended successor.
Fix #385
=> replace image i/o from scipy.misc by imageio

intro/numpy/examples/plot_mandelbrot.py
the code applies the iteration for all array elements, some of which are
expected to overflow.
fix #480
=> suppress warnings for mandelbrot example

advanced/advanced_numpy/index.rst, advanced/interfacing_with_c/interfacing_with_c.rst, conf.py, intro/help/help.rst, intro/numpy/advanced_operations.rst, intro/numpy/elaborate_arrays.rst
Updates links from old URL at scipy.org to the current URL hosting numpy documentation.
Also fixes a few broken links to NumPy C-API docs.
=> DOC: Update links to numpy.org doc site.

packages/statistics/index.rst
Hi,
I updated the link to point to the current PyMC homepage.
Thank you for your great work on the lecture notes!
=> link to PyMC3 instead of PyMC2

advanced/advanced_numpy/index.rst, intro/numpy/operations.rst
I had noticed that a warning box in the numpy operations section illustrated behavior from numpy versions prior to 1.13: see [these release notes](https://numpy.org/devdocs/release/1.13.0-notes.html#ufunc-behavior-for-overlapping-inputs) for details (thanks to @seberg for pointing me to these specific docs). 
In this PR, I updated the text to more accurately reflect the behavior of NumPy since version 1.13. The new text might go into too much detail to really fit in this section, so other possible alternatives might be:
1. Remove the warning box altogether
2. Replace the `.. warning` with a `.. note` (or other "informational" directive) that indicates that the transpose returns a view, without the additional `a += a.T` example.
=> Update `.. warning` on NumPy in-place operations with views

advanced/advanced_numpy/index.rst, intro/numpy/array_object.rst, intro/numpy/elaborate_arrays.rst
First off, thanks so much to the authors/contributors of the SLN - they are a great resource for learning & illustrating the features of the scientific Python ecosystem!
A few minor changes from a recent re-read of the NumPy articles (intro & advanced):
* A wording suggestion (indexes->indices for consistency with the rest of the document)
* Convert instances of `str(arr.data)` to `bytes(arr.data)` when used to illustrate the contents of the `data` attribute of arrays
* Explicitly convert a couple instances of floats in scientific notation -> int so they are valid input to `np.zeros`
=> Minor updates to the articles on NumPy

intro/intro.rst
There is a small typo in intro/intro.rst.
Should read `integrates` rather than `itegrates`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, itegrates -> integrates

intro/scipy/examples/plot_fftpack.py
The inner plot incorrectly has the peak at 0.25 where the peak frequency should be at 0.2.
Explanation of fix: 
The x axis plots the `freqs` variable after removing the non-positive values while the y axis plots `power` without removing the non-positive values and that's what causing the error. The fist just removes the non-positive values in the y axis as well.
=> Fix inner plot in fftpack example

README.rst
It might be cool if <scipy-lectures.org> would default to HTTPS as well.
Also it seems like there is a more recent Zenodo release than the one currently linked.
=> Update links in readme

build_tools/install.sh, requirements.txt
Use conda-forge as it has better and more up-to-date packages. Conda-forge also pulled in a version of imageio that requires Python 3.7. I pinned imagio to the last version that supported Python 3.6. I will deal with the Python 3.6 in a separate PR. I am trying to get a few minor things cleaned up in small PRs so that it will be easier to review a bgger PR later.
=> Use conda forge

.circleci/config.yml, .github/workflows/test.yml, advanced/advanced_numpy/index.rst, advanced/image_processing/examples/plot_watershed_segmentation.py, advanced/image_processing/index.rst, advanced/mathematical_optimization/index.rst, advanced/scipy_sparse/lil_matrix.rst, intro/image_processing/image_processing.rst, intro/matplotlib/examples/plot_imshow.py, intro/numpy/array_object.rst, intro/numpy/elaborate_arrays.rst, intro/numpy/exercises.rst, intro/scipy.rst, intro/summary-exercises/examples/plot_cumulative_wind_speed_prediction.py, intro/summary-exercises/examples/plot_gumbell_wind_speed_prediction.py, intro/summary-exercises/stats-interpolate.rst, packages/scikit-image/examples/plot_segmentations.py, packages/scikit-image/index.rst, packages/scikit-learn/examples/plot_separator.py, packages/scikit-learn/index.rst, packages/statistics/examples/plot_iris_analysis.py, packages/statistics/examples/plot_pandas.py, packages/statistics/examples/solutions/plot_brain_size.py, packages/statistics/index.rst, requirements.txt
Per NEP 29, many core packages dropped support for Python 3.7 after Dec 26, 2021. So we need Python 3.8 to use the latest versions of those packages.
=> Use Python 3.8+ and bump dependencies

.github/workflows/test.yml, Makefile, intro/image_processing/image_processing.rst, intro/matplotlib/examples/plot_plot3d-2.py, intro/matplotlib/examples/plot_plot3d.py, intro/numpy/exercises.rst, packages/statistics/examples/plot_regression_3d.py, requirements.txt
A few new releases came out in the last few days joblib 1.2, matplotlib 3.6, and pywavelets 1.4. There was a minor doctest output issue with  matplotlib 3.6. This PR fixes that and cleans up two other minor issues I missed in my last PR.
=> Support Matplotlib 3.6

conf.py
This removes all the warnings due to old settings in the sphinx conf.py file. There are still warnings during `make html`, but those are related to actual content and will be addressed in a future PR.
=> Fix sphinx warnings from configuration file

advanced/image_processing/examples/plot_GMM.py, advanced/image_processing/examples/plot_clean_morpho.py, advanced/image_processing/examples/plot_find_object.py, advanced/image_processing/examples/plot_granulo.py, advanced/image_processing/examples/plot_greyscale_dilation.py, advanced/image_processing/examples/plot_histo_segmentation.py, advanced/image_processing/examples/plot_measure_data.py, advanced/image_processing/examples/plot_propagation.py, advanced/image_processing/examples/plot_radial_mean.py, advanced/image_processing/examples/plot_synthetic_data.py, advanced/image_processing/index.rst, intro/image_processing/image_processing.rst, intro/scipy/examples/plot_image_filters.py, intro/summary-exercises/answers_image_processing.rst, packages/scikit-image/examples/plot_boundaries.py, packages/scikit-image/examples/plot_labels.py, packages/scikit-image/index.rst
@pdebuyl Rebased on main and ready to merge.
Using the aliases of builtin types like np.int was deprecated in 1.20:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Use builtin types

packages/scikit-learn/index.rst, packages/statistics/index.rst
Before 
```
======================= 40 passed, 13 warnings in 17.05s =======================
```
After
```
======================= 40 passed, 9 warnings in 26.52s ========================
```
=> Fix more warnings

conf.py
Otherwise Sphinx complains that the default is a bool, but that the Makefile specifies a string.
=> Set default for `plot_gallery` to string, to avoid Sphinx type checking warning

CONTRIBUTING.rst, requirements.txt
How to create a virtual environment (pip / conda) is best left for somewhere else.
Note that the `environment.yml` is now gone, so no point in maintaining separate conda instructions.  We could add it back again if that is helpful, but then we have to synchronize the two files.
=> Simplify installation instructions

advanced/mathematical_optimization/index.rst, conf.py, includes/big_toc_css.rst, includes/bigger_toc_css.rst, intro/scipy/index.rst
@jarrodmillman Please review 3491fcf9cdcf839292023ed2aa5670f064b955b0 carefully; looks like Sphinx gallery started using 1-based indexing at some point. However, with your renaming of certain images, I only had to change those with low numbers?
=> Fix warnings

themes/scipy_lectures/static/nature.css_t
List item contents are now wrapped in `<p></p>` tags.  This workaround is fine for single item lists, but not for longer sentences, but it looks as though `rst-class:: horizontal` is exclusively used for short items, such as pre-requisites.
Partially resolves https://github.com/scipy-lectures/scipy-lecture-notes/issues/550
=> Fix rendering of horizontal lists

advanced/index.rst, advanced/mathematical_optimization/index.rst, intro/index.rst, intro/numpy/index.rst, packages/index.rst
Oddly, sphinx does not provide a good way to do this out of the box. Their recommended approach is to rename included files to have some other extension, so Sphinx does not try to build pages for those files :thinking: 
Instead, I am using a pattern I found elsewhere in the lecture notes.
Partially closes https://github.com/scipy-lectures/scipy-lecture-notes/issues/550
=> Use :start-line: to avoid rendering of :orphan: from included files

themes/scipy_lectures/static/nature.css_t
Sphinx now renders these as `<aside class="topic">`.
This is the box in which the prerequisites appear.
Partially closes https://github.com/scipy-lectures/scipy-lecture-notes/issues/550
=> Fix topic rendering

docutils.conf
This is a change introduced in `docutils` 0.18:
- Only specify table column widths, if the `"widths" option`_ is set and is not "auto" (fixes bug #426). https://sourceforge.net/p/docutils/bugs/426/
By default, `docutils` now lets the browser decide the width of a table. Usually, that's what you want, but we prefer our tables to have two equally sized columns when doing comparisons.
`docutils` uses the following conditions to determine whether to avoid writing a colgroup tag:
```python
if 'colwidths-auto' in node.parent.parent['classes'] or (
'colwidths-grid' not in self.settings.table_style
and 'colwidths-given' not in node.parent.parent['classes']):
return
```
So, after adding `table_style: colwidths_grid` to `docutils.py`, we get the old behavior back. To get browser column balancing, …
=> docutils: generate colspec for tables

themes/scipy_lectures/static/nature.css_t
Sphinx now renders these as definition lists
Partially addresses https://github.com/scipy-lectures/scipy-lecture-notes/issues/550
=> Restore styling of pro/con tables

requirements.txt
TODO: math roles aren't rendered with sphinx 5.3
=> Pin to sphinx 5.2.3

CONTRIBUTING.rst, Makefile, README.rst, about.rst, advanced/index.rst, conf.py, guide/index.rst, index.rst, intro/help/help.rst, intro/index.rst, intro/intro.rst, intro/language/reusing_code.rst, intro/matplotlib/index.rst, intro/numpy/operations.rst, packages/index.rst, packages/scikit-image/index.rst, preface.rst, pyximages/README.md
As discussed during today at the Scientific Python summit, I propose to rename the project to "Scientific Python lecture notes".
This removes yet another confusion in the current state of the ecosystem and clarify that this is not part of the SciPy library (which is a trademark concern on its own.)
If/once this is approved, the name of the repository should be changed accordingly. (And there is going to be the question about the web domain and where/how this website is administrated.)
cc @jarrodmillman
=> Rename project to Scientific Python lecture notes

intro/scipy/index.rst
In gh-579, we discussed removing this content about the error messages, which are quite readable should the user encounter them. This frees up some space for a brief mention of another topic - structured matrices.
=> ENH: scipy.linalg: replace content about errors

packages/scikit-image/index.rst
- Clean up library description and related libraries
- Avoid using `skimage.io.data_dir` by saving an example image to disk
- Use `import skimage as ski` convention
=> Review skimage module up to `io`

packages/scikit-learn/examples/plot_eigenfaces.py, packages/scikit-learn/index.rst
Closes gh-560
I removed the header from the index rather than `plot_eigenfaces.py` in case `plot_eigenfaces.py` is accessed as a stand-alone document. Need to check with the sidebar thing works properly.
=> MAINT: remove duplicate eigenfaces header

advanced/advanced_numpy/index.rst
Avoid
```
1259 - But it's integrated into Python  (e.g. strings support it)
1260
1261 Mini-exercise using `Pillow <https://python-pillow.org/>`_ (Python
1262 Imaging Library):
1263
1264 .. seealso:: pilbuffer.py
1265
1266 >>> from PIL import Image
1267 >>> data = np.zeros((200, 200, 4), dtype=np.int8)
1268 >>> data[:, :] = [255, 0, 0, 255] # Red
UNEXPECTED EXCEPTION: DeprecationWarning('NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 255 to int8 will fail in the future.\nFor the old behavior, usually:\n    np.array(value).astype(dtype)\nwill give the desired result (the cast overflows).')
Traceback (most recent call last):
File "/usr/lib64/python3.11/doctest.py", line 1351, in __run
exec(compile(example.source, filename, "single", …
```
=> Fix out-of-bound  conversion warning

packages/scikit-learn/index.rst
Avoid
```
packages/scikit-learn/index.rst::index.rst
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
warnings.warn(
```
The `LinearSVC` docstrings reads:
```
dual : bool, default=True
Select the algorithm to either solve the dual or primal
optimization problem. Prefer dual=False when n_samples > n_features.
```
and
```
>>> X_train.shape
(1347, 64)
```
where `X` is `(n_samples, n_features)`.
=> Use primal to improve convergence

advanced/advanced_numpy/index.rst
Example gufuncs will have to be found elsewhere.
Closes #618
=> Remove usage of deprecated numpy.core.umath_tests

intro/scipy/index.rst
`.. only:: latex` and `.. only:: html` are both parsed when compiling, thus it cannot be used to "branch" table of contents for the two output formats.
Instead, we switch to `.. only:: html` for selecting the headers.
=> Prevent "X is already assigned section numbers" warnings

Makefile, conf.py, themes/scientific_python_lectures/layout.html
Since we're hosting on GitHub Pages, we don't have the option of using a 301 Moved Permanently.
But this is a route recommended by Google:
https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls https://developers.google.com/search/docs/crawling-indexing/301-redirects#metarefresh
=> Add client-side redirect to lectures.scientific-python.org

advanced/debugging/to_debug.py, advanced/debugging/to_debug_solution.py, advanced/debugging/wiener_filtering.py, advanced/image_processing/examples/plot_GMM.py, advanced/image_processing/examples/plot_clean_morpho.py, advanced/image_processing/examples/plot_denoising.py, advanced/image_processing/examples/plot_face_denoise.py, advanced/image_processing/examples/plot_face_tv_denoise.py, advanced/image_processing/examples/plot_find_edges.py, advanced/image_processing/examples/plot_find_object.py, advanced/image_processing/examples/plot_granulo.py, advanced/image_processing/examples/plot_greyscale_dilation.py, advanced/image_processing/examples/plot_histo_segmentation.py, advanced/image_processing/examples/plot_measure_data.py, advanced/image_processing/examples/plot_propagation.py, advanced/image_processing/examples/plot_spectral_clustering.py, advanced/image_processing/examples/plot_synthetic_data.py, advanced/mathematical_optimization/examples/helper/compare_optimizers.py, intro/matplotlib/examples/pretty_plots/plot_text_ext.py, intro/numpy/examples/plot_chebyfit.py, intro/numpy/examples/plot_polyfit.py, intro/scipy/examples/plot_fftpack.py, intro/scipy/examples/plot_interpolation.py, packages/scikit-image/examples/plot_labels.py, packages/scikit-learn/examples/plot_polynomial_regression.py, packages/scikit-learn/examples/plot_svm_non_linear.py
It looks like the intent was to switch from use of `RandomState`s to `Generator`s, but the transition is incomplete. I searched for occurences of `random.rand` (which also finds `randn` and `randint`) and replaced them.
@tupui would you check me here? Some things to look for:
- `rng` is defined where it's used
- `rng` is defined only once (i.e. I didn't add it a new one where it was unneeded)
- `random.rand` with separate positional arguments has been replaced with `rng.random` with single positional argument
- `random.randn` with a positional arguments has been changed to `rng.normal` with `size` keyword argument, etc.
- `random.randint` has been replaced with `rng.integers` (signatures are compatible, right?)
- I didn't miss anything obvious?
=> MAINT: use random Generator instead of RandomState

intro/scipy/examples/plot_fftpack.py, intro/scipy/examples/solutions/plot_fft_image_denoise.py, intro/scipy/examples/solutions/plot_image_blur.py, intro/scipy/examples/solutions/plot_periodicity_finder.py, intro/scipy/index.rst
`scipy.fftpack` is considered legacy; this updates uses of `scipy.fftpack` to use `scipy.fft`, instead. To avoid unnecessary churn, I didn't modify filenames that include `fftpack`.
=> Replace use of scipy.fftpack with scipy.fft

intro/scipy/examples/plot_interpolation.py, intro/scipy/index.rst
This is a fairly minimal update to the interpolate section. Important points are that the example no longer uses the legacy function `interp1d`, and it highlights the distinction between the two main uses of splines: smoothing and interpolation.
One thing I could consider doing including in this PR is to simplify variable names. I maintained the existing style, but I would find the code easier to read with simpler variable names like `t` and `x`. LMK what you think.
In follow-up PRs, I could:
- Show how to take the `derivative` and `antiderivative` of a spline in the text.
- Show how to get the roots of a spline in the text.
- Create a separate example that shows how to create an inverse of a function.
LMK what you'd be interested in.
=> ENH: Update scipy.interpolate section

intro/language/standard_library.rst
=> Update standard library lesson

intro/scipy/index.rst
Addresses most elements of gh-730. I don't think I'll add an example of finding roots because that is partially addressed with the inverse interpolation example here, and the `roots` method is only available for `PPoly` splines, which we're not showing in this example already.
=> ENH: scipy.interpolate: add derivative/antiderivative and inverse interpolation examples

packages/scikit-learn/index.rst, requirements.txt
Fixes the issue seen in https://github.com/scipy-lectures/scientific-python-lectures/pull/761
To make `train_test_split` deterministic, we need to set the `random_state`.
=> Set random state when splitting data to update scikit-learn

advanced/scipy_sparse/bsr_array.rst, advanced/scipy_sparse/coo_array.rst, advanced/scipy_sparse/csc_array.rst, advanced/scipy_sparse/csr_array.rst, advanced/scipy_sparse/dia_array.rst, advanced/scipy_sparse/dok_array.rst, advanced/scipy_sparse/lil_array.rst, requirements.txt
I added the other repr changes for scipy 1.14 in the scipy-sparse lectures. hopefully the tests are green
=> Fix repr changes in sparse for Scipy 1.14

advanced/scipy_sparse/examples/direct_solve.py, advanced/scipy_sparse/examples/lobpcg_sakurai.py, advanced/scipy_sparse/examples/pyamg_with_lobpcg.py
Still needs work (but it runs now):
```
$ python advanced/scipy_sparse/examples/lobpcg_sakurai.py
/home/jarrod/src/scientific-python-lectures/advanced/scipy_sparse/examples/lobpcg_sakurai.py:47: UserWarning: Exited at iteration 500 with accuracies 
[1158100.72206623    8047.95297708    6596.98347933]
not reaching the requested tolerance 1e-06.
Use iteration 0 instead with accuracy 
2.0908717846394285.
eigs, vecs, resnh = sp.sparse.linalg.lobpcg(
/home/jarrod/src/scientific-python-lectures/advanced/scipy_sparse/examples/lobpcg_sakurai.py:47: UserWarning: Exited postprocessing with accuracies 
[5.4496576  0.42115509 0.40180266]
not reaching the requested tolerance 1e-06.
eigs, vecs, resnh = sp.sparse.linalg.lobpcg(
Results by LOBPCG for n=2500
[1.6384843  0.17288616 0.16788489]
Exact …
```
=> Fix LOBPCG Sakurai typos

CONTRIBUTING.rst
Update CONTRIBUTING.rst to fix typo from idomatic to idiomatic.
=> Update CONTRIBUTING.rst to fix typo from idomatic to idiomatic

.github/workflows/test.yml, intro/matplotlib/index.rst
Waiting on https://github.com/apache/arrow/issues/43519
=> Test on Python 3.13

packages/scikit-learn/examples/plot_separator.py
Fix typo from ploints to points in plot_separator.py.
=> Fix typo from ploints to points in plot_separator.py
